//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineLeaveApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTOApplication
    {
        public int CTOApplicationID { get; set; }
        public Nullable<short> EmployeeID { get; set; }
        public Nullable<System.DateTime> DateApplied { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
