//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineLeaveApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveApplicationDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LeaveApplicationDetail()
        {
            this.LeaveApplicationDetailInclusiveDates = new HashSet<LeaveApplicationDetailInclusiveDate>();
        }
    
        public int LeaveApplicationDetailID { get; set; }
        public Nullable<int> LeaveApplicationID { get; set; }
        public Nullable<byte> TypeOfLeaveID { get; set; }
        public Nullable<bool> WithinThePhilippines { get; set; }
        public string WithinThePhilippinesAbroadLocation { get; set; }
        public Nullable<bool> InHospital { get; set; }
        public string InHospitalOutPatientIllness { get; set; }
        public string SpecialLeaveBenefits { get; set; }
        public Nullable<bool> CompletionOfMastersDegree { get; set; }
        public Nullable<bool> BARBoardExaminationReview { get; set; }
        public Nullable<bool> MonetizationOfLeaveCredits { get; set; }
        public Nullable<bool> TerminalLeave { get; set; }
    
        public virtual LeaveApplication LeaveApplication { get; set; }
        public virtual TypeOfLeave TypeOfLeave { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveApplicationDetailInclusiveDate> LeaveApplicationDetailInclusiveDates { get; set; }
    }
}
