//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineLeaveApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveApplicationAttachment
    {
        public int LeaveApplicationAttachmentID { get; set; }
        public Nullable<int> LeaveApplicationID { get; set; }
        public byte[] UploadedFile { get; set; }
        public string FileName { get; set; }
    
        public virtual LeaveApplication LeaveApplication { get; set; }
    }
}
