//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineLeaveApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveApplication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LeaveApplication()
        {
            this.LeaveApplicationDetails = new HashSet<LeaveApplicationDetail>();
            this.LeaveApplicationSubmissions = new HashSet<LeaveApplicationSubmission>();
            this.LeaveApplicationAttachments1 = new HashSet<LeaveApplicationAttachment>();
        }
    
        public int LeaveApplicationID { get; set; }
        public Nullable<short> EmployeeID { get; set; }
        public Nullable<System.DateTime> DateApplied { get; set; }
        public Nullable<short> ReceivedBy { get; set; }
        public Nullable<short> ReviewedBy { get; set; }
        public Nullable<short> ApprovedBy { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
        public virtual Employee Employee3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveApplicationDetail> LeaveApplicationDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveApplicationSubmission> LeaveApplicationSubmissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveApplicationAttachment> LeaveApplicationAttachments1 { get; set; }
    }
}
