//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineLeaveApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveApplicationSubmission
    {
        public int LeaveApplicationSubmissionID { get; set; }
        public Nullable<int> LeaveApplicationID { get; set; }
        public Nullable<short> SubmittedBy { get; set; }
        public Nullable<System.DateTime> DateSubmitted { get; set; }
        public Nullable<short> ReceivedBy { get; set; }
        public Nullable<short> Status { get; set; }
        public string Remarks { get; set; }
    
        public virtual LeaveApplication LeaveApplication { get; set; }
    }
}
