//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineLeaveApplication
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnlineLeaveApplicationEntities : DbContext
    {
        public OnlineLeaveApplicationEntities()
            : base("name=OnlineLeaveApplicationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<LeaveApplication> LeaveApplications { get; set; }
        public virtual DbSet<LeaveApplicationDetail> LeaveApplicationDetails { get; set; }
        public virtual DbSet<LeaveApplicationDetailInclusiveDate> LeaveApplicationDetailInclusiveDates { get; set; }
        public virtual DbSet<Office> Offices { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<RegionalOrder> RegionalOrders { get; set; }
        public virtual DbSet<RegionalOrderDetail> RegionalOrderDetails { get; set; }
        public virtual DbSet<RegionalOrderDetailDate> RegionalOrderDetailDates { get; set; }
        public virtual DbSet<TypeOfLeave> TypeOfLeaves { get; set; }
        public virtual DbSet<LeaveApplicationSubmission> LeaveApplicationSubmissions { get; set; }
        public virtual DbSet<CTOApplication> CTOApplications { get; set; }
        public virtual DbSet<LeaveApplicationAttachment> LeaveApplicationAttachments { get; set; }
        public virtual DbSet<MainOffice> MainOffices { get; set; }
    }
}
