//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineLeaveApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionalOrderDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RegionalOrderDetail()
        {
            this.RegionalOrderDetailDates = new HashSet<RegionalOrderDetailDate>();
        }
    
        public int RegionalOrderDetailID { get; set; }
        public Nullable<int> RegionalOrderID { get; set; }
        public Nullable<short> EmployeeID { get; set; }
        public string Venue { get; set; }
        public string Remarks { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual RegionalOrder RegionalOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegionalOrderDetailDate> RegionalOrderDetailDates { get; set; }
    }
}
