//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineLeaveApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionalOrderDetailDate
    {
        public int RegionalOrderDetailDateID { get; set; }
        public Nullable<int> RegionalOrderDetailID { get; set; }
        public Nullable<System.DateTime> ActivityDate { get; set; }
    
        public virtual RegionalOrderDetail RegionalOrderDetail { get; set; }
    }
}
