//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineLeaveApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionalOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RegionalOrder()
        {
            this.RegionalOrderDetails = new HashSet<RegionalOrderDetail>();
        }
    
        public int RegionalOrderID { get; set; }
        public string RegionalOrderNumber { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> RegionalOrderDate { get; set; }
        public Nullable<short> Signatory { get; set; }
        public Nullable<bool> isCompensatoryOvertimeCredit { get; set; }
        public string Remarks { get; set; }
        public byte[] UploadedFile { get; set; }
        public string FilePath { get; set; }
        public string OriginalFileName { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegionalOrderDetail> RegionalOrderDetails { get; set; }
    }
}
